export type VocabCardRow = {
  id: string;
  user_id: string;
  front: string;
  back: string;
  due: string;
  stability: number;
  difficulty: number;
  elapsed_days: number;
  scheduled_days: number;
  reps: number;
  lapses: number;
  state: number;
  last_review: string | null;
  created_at: string;
  category: string | null;
  related_words: string | null;
  collocation: string | null;
  etymology: string | null;
  word_family: string | null;
};
